require(phyclust)
require(dplyr)
require(plyr)
require(permute)
require(ggplot2)

#This function returns a list of two objects, the first object is a list
# of phyclust objects generated by the call to find.best and the second is
# a dataframe from these clusters that is used as the input for the clustergram
# function
many_phyclust <- function(X, ks) {
    clusters <- list()
    df <- data.frame(obs=integer(), i=integer(),k=integer(),cluster=integer())
    for (i in seq_along(ks)){
        cl <- find.best(X,ks[i])
        clusters <- c(clusters,list(cl))
        temp <- data.frame(obs = seq_len(nrow(X)), i = i, k = ks[i], cluster = cl$class.id)
        df <- dplyr::bind_rows(df,temp)
    }
    return(list(clusters,df))   
    }

reorder <- function(clusters){
    for(x in 1:max(clusters$i)){
        if(x == 1){
            adj.clstr <- subset(clusters, i == 1)$cluster
            new.clstr <- adj.clstr
        }
        else{
            sub <- subset(clusters, i == x)
            CTRL <- how()
            CTRL$maxperm = Inf
            p <- allPerms(1:max(sub$cluster), control=CTRL)
            k.perm <- sapply(1:dim(p)[1], function(y) p[y,sub$cluster])
            k.diff <- sapply(1:dim(p)[1], function(z) sum((adj.clstr-k.perm[,z])^2))
            m <-match(min(k.diff),k.diff)
            adj.clstr <-k.perm[,m]
            new.clstr <- c(new.clstr,adj.clstr)
        } 
    }
    clusters$cluster <- new.clstr
    return(clusters)
}

line.width <- function(clusters){
    space <- diff(range(clusters$cluster))
    line.width <- 0.5*space/length(unique(clusters$obs))
    clusters$line.width <- line.width
    return(clusters)
}

center <- function(x) x - mean(range(x))

adj <- function(clusters,s){
    r <- diff(range(clusters$cluster))
    clusters$adjcenter <-clusters$center*(s/r)
    return(clusters)
} 

adjcenter <- function(clusters){
    space <- diff(range(clusters$cluster))
    clusters <-plyr::ddply(clusters,.(i),transform, center = center(cluster))
    clusters <-plyr::ddply(clusters,.(i),adj, s = space)
    return(clusters)
}

height <- function(x,l){
    n <- length(x)
    l <- mean(l)
    first <- mean(x) - n*0.5*l
    last <- mean(x) +n*0.5*l
    seq(first, by=l,length.out=n)
}

#Takes the dataframe output from many_phyclust and adds the additional columns:
# line.width, center, adjcenter and height to allow for plotting of the clustergram
clustergram <- function(clusters){
    clusters <-reorder(clusters)
    clusters <-line.width(clusters)
    clusters <- adjcenter(clusters)
    clusters <-plyr::ddply(clusters,.(i,cluster),transform, height = height(adjcenter,line.width))
}

plot.clustergram <- function(clusters){
    i_pos <- !duplicated(clusters$i)
    means <- plyr::ddply(clusters,.(cluster,i),summarise,min=min(height),max=max(height))
    clusters$cluster <- as.factor(clusters$cluster)
    ggplot(clusters, aes(i)) +
        geom_line(aes(y = height, group = obs, colour = height)) +
        scale_colour_gradientn(colours=topo.colors(10)) +
        geom_errorbar(data = means,aes(ymin = min, ymax = max),width = 0.1) +
        scale_x_continuous("Clusters", breaks = clusters$i[i_pos], labels = clusters$k[i_pos]) +
        theme_bw() + 
        theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), axis.title.y=element_blank()) +
        guides(colour=FALSE)
}








